# Numpy

In [1]:
import numpy as np

In [2]:
data = np.array([[ 0.9526, -0.246 , -0.8856],
[ 0.5639, 0.2379, 0.9104]])

In [3]:
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [4]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [5]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim, arr2.shape, arr2.dtype

(2, (2, 4), dtype('int32'))

In [15]:
dir(arr2)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2))

array([[[1.24796458e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.78020168e-306, 3.76231868e+174]],

       [[7.48013995e-091, 6.49265610e+169],
        [1.26054657e-076, 1.16066162e-046],
        [3.99910963e+252, 8.34668371e-309]]])

It’s not safe to assume that np.empty will return an array of all zeros. In many cases, as previously shown, it will return uninitialized garbage values.

In [24]:
np.zeros_like(arr2), np.ones_like(arr2), np.empty_like(arr2)

(array([[0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[          0,           0,   419083616,         588],
        [          0, -2147483648,           0,      524288]]))

## Data type for ndarrays

In [31]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [32]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [33]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

In [34]:
arr1, arr2

(array([1., 2., 3.]), array([1, 2, 3]))

In [35]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr.dtype

dtype('int32')

In [37]:
float_arr = arr.astype(np.float64)

In [38]:
float_arr.dtype

dtype('float64')

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [40]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

Converting float into int type leads to info loss

In [46]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [47]:
numeric_strings.astype(float)  # numpy recongnized it is np.float

array([ 1.25, -9.6 , 42.  ])

In [48]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

## Operations between Arrays and Scalars
### Vectorization

In [49]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [50]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [51]:
arr * arr, arr-arr

(array([[ 1.,  4.,  9.],
        [16., 25., 36.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

Operations are done element wise

In [52]:
1 / arr, arr**0.5

(array([[1.        , 0.5       , 0.33333333],
        [0.25      , 0.2       , 0.16666667]]),
 array([[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]))

## Basic Indexing and Slicing

In [53]:
arr = np.arange(10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[5:8]

array([5, 6, 7])

In [56]:
arr[5:8] = 12 # example of broadcasting

In [57]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr_slice = arr[5:8]   #This does not copy. So any modification to arr_slice will be reflected in original array too

In [61]:
arr_slice[1] = 12345

In [62]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [63]:
arr_slice[:] = 64

In [64]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays.

In [65]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [66]:
arr2d[2]

array([7, 8, 9])

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[0][2]

3

In [69]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [70]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr3d[0][0]

array([1, 2, 3])

In [74]:
old_values = arr3d[0].copy()

In [75]:
arr3d[0] = 42  # Both scaler values and arrays can be assigned to n-d array

In [76]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values

In [100]:
arr3d[:1, :1, 1:]

array([[[2, 3]]])

In [101]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

When slicing like this, you always obtain array views of the same number of dimensions.
By mixing integer indexes and slices, you get lower dimensional slices.

In [104]:
arr2d[1, :2]

array([4, 5])

In [105]:
arr2d[2, :1]

array([7])

In [107]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

## Boolean Indexing

In [108]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [115]:
data = np.random.randn(7, 4)

In [117]:
names, data

(array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4'),
 array([[ 2.50524260e-01,  1.18892659e+00, -3.94106840e-01,
         -7.15199087e-01],
        [ 1.16357778e-01, -9.95982529e-02, -2.15311472e-01,
         -4.98182741e-01],
        [ 1.29493112e-01,  5.04229183e-01, -5.97068840e-01,
          6.94739383e-01],
        [ 1.07930586e+00, -6.35273373e-01,  6.53408111e-01,
          2.69321712e-01],
        [ 2.83629322e-01,  1.02373388e-01, -4.10336728e-01,
          1.27892620e+00],
        [-2.37466382e-01, -6.07118874e-02, -1.02760233e+00,
         -1.87442935e+00],
        [-7.01545685e-01,  3.09950585e+00,  5.74209295e-04,
          7.95822973e-01]]))

In [118]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [119]:
data[names == 'Bob']

array([[ 0.25052426,  1.18892659, -0.39410684, -0.71519909],
       [ 1.07930586, -0.63527337,  0.65340811,  0.26932171]])

In [120]:
data[names == 'Bob', 2:]

array([[-0.39410684, -0.71519909],
       [ 0.65340811,  0.26932171]])

In [121]:
mask = (names == 'Bob') | (names == 'Will')

In [122]:
mask

array([ True, False,  True,  True,  True, False, False])

In [123]:
data[mask]

array([[ 0.25052426,  1.18892659, -0.39410684, -0.71519909],
       [ 0.12949311,  0.50422918, -0.59706884,  0.69473938],
       [ 1.07930586, -0.63527337,  0.65340811,  0.26932171],
       [ 0.28362932,  0.10237339, -0.41033673,  1.2789262 ]])

Selecting data from an array by boolean indexing always creates a copy of the data, even if the returned array is unchanged.
The Python keywords and and or do not work with boolean arrays.

## Fancy Indexing

In [124]:
arr = np.empty((8, 4))